// ============================================================================
// Insight / digest email renderers — pure (data in, HTML/plain-text out).
// ============================================================================
// Extracted from routes/insights.js (route-file split). insights.js imports
// and re-exports these, so `require("./routes/insights").renderInsightEmail`
// keeps working for every existing caller and test.

// Render insight text as styled HTML email matching app aesthetic
// S2 — Weekly digest email body. Differs from renderInsightEmail in that the
// content is the *structured running summary* (trends, pending_actions,
// alerts), not a fresh insight run. Designed for a Monday-morning habit
// channel — cheap to render (no AI call) and visually distinct so users can
// tell it apart from the cadence-driven insights email.
function renderWeeklyDigestEmail(summary, freshness) {
  const arrow = (d) => d === "up" ? "↑" : d === "down" ? "↓" : "→";
  const sev = (s) => s === "high" ? "#eb6b6b" : s === "medium" ? "#f0c36d" : "#9fd4c9";
  const trendsHtml = (summary.trends || []).slice(0, 8).map(t =>
    `<li style="margin:6px 0;color:#cccccc;">
       <span style="color:#d4a574;">${arrow(t.direction)}</span>
       <strong style="color:#ffffff;">${escapeHtml(t.category || "")}</strong>
       ${t.magnitude ? `<span style="color:#888;">(${escapeHtml(t.magnitude)})</span>` : ""}
       ${t.since_when ? `<span style="color:#777;font-size:11px;"> since ${escapeHtml(t.since_when)}</span>` : ""}
     </li>`
  ).join("");
  const actionsHtml = (summary.pending_actions || []).slice(0, 10).map(a =>
    `<li style="margin:6px 0;color:#cccccc;">
       <strong style="color:#ffffff;">${escapeHtml(a.description || "")}</strong>
       ${a.urgency ? `<span style="color:${sev(a.urgency)};font-size:11px;"> [${escapeHtml(a.urgency)}]</span>` : ""}
     </li>`
  ).join("");
  const alertsHtml = (summary.alerts || []).slice(0, 10).map(a =>
    `<li style="margin:6px 0;color:#cccccc;">
       <strong style="color:${sev(a.severity)};">${escapeHtml(a.message || "")}</strong>
       ${a.severity ? `<span style="color:#888;font-size:11px;"> [${escapeHtml(a.severity)}]</span>` : ""}
     </li>`
  ).join("");
  const completedHtml = (summary.completed_goals || []).slice(0, 5).map(g =>
    `<li style="margin:6px 0;color:#9fd4c9;">
       ${escapeHtml(g.goal_name || "")}
       ${g.completed_date ? `<span style="color:#888;font-size:11px;"> (${escapeHtml(g.completed_date)})</span>` : ""}
     </li>`
  ).join("");

  const section = (title, color, html) => html ? `
    <h3 style="color:${color};font-size:15px;margin:20px 0 8px;font-weight:600;">${title}</h3>
    <ul style="list-style:none;padding:0;margin:0;">${html}</ul>` : "";

  const freshnessFooter = freshness ? `
    <p style="color:#666666;font-size:11px;margin:4px 0 0;">
      Last sync: ${freshness.last_txn_sync_at ? new Date(freshness.last_txn_sync_at).toLocaleDateString() : "never"}
    </p>` : "";

  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#080b12;font-family:Inter,system-ui,sans-serif;">
    <div style="max-width:640px;margin:0 auto;padding:32px 24px;">
      <div style="text-align:center;margin-bottom:24px;">
        <h1 style="color:#d4a574;font-size:22px;margin:12px 0 4px;font-weight:300;">Your Weekly Financial Digest</h1>
        <p style="color:#888888;font-size:12px;margin:0;">${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
      </div>
      <div style="background:#0f1320;border:1px solid #1a1f35;border-radius:12px;padding:24px;">
        ${section("Trends", "#d4a574", trendsHtml)}
        ${section("Pending Actions", "#f0c36d", actionsHtml)}
        ${section("Active Alerts", "#eb6b6b", alertsHtml)}
        ${section("Recently Completed", "#9fd4c9", completedHtml)}
        ${!trendsHtml && !actionsHtml && !alertsHtml && !completedHtml
          ? '<p style="color:#888;text-align:center;margin:24px 0;">No tracked items this week. Run an insight from Settings → AI Insights to start building your memory.</p>'
          : ""}
      </div>
      <div style="text-align:center;margin-top:24px;padding-top:16px;border-top:1px solid #1a1f35;">
        <p style="color:#666666;font-size:11px;margin:0;">Generated by Perfin · Weekly Digest</p>
        ${freshnessFooter}
      </div>
    </div>
  </body></html>`;
}

function renderWeeklyDigestText(summary) {
  const arrow = (d) => d === "up" ? "^" : d === "down" ? "v" : "-";
  const lines = ["YOUR WEEKLY FINANCIAL DIGEST", ""];
  if (summary.trends && summary.trends.length) {
    lines.push("TRENDS");
    for (const t of summary.trends.slice(0, 8)) {
      lines.push(`  ${arrow(t.direction)} ${t.category || ""}` +
        (t.magnitude ? ` (${t.magnitude})` : "") +
        (t.since_when ? ` since ${t.since_when}` : ""));
    }
    lines.push("");
  }
  if (summary.pending_actions && summary.pending_actions.length) {
    lines.push("PENDING ACTIONS");
    for (const a of summary.pending_actions.slice(0, 10)) {
      lines.push(`  - ${a.description}` + (a.urgency ? ` [${a.urgency}]` : ""));
    }
    lines.push("");
  }
  if (summary.alerts && summary.alerts.length) {
    lines.push("ALERTS");
    for (const a of summary.alerts.slice(0, 10)) {
      lines.push(`  ! ${a.message}` + (a.severity ? ` [${a.severity}]` : ""));
    }
    lines.push("");
  }
  return lines.join("\n");
}

function escapeHtml(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

// #19 — Daily "what changed since yesterday" digest. Mirrors runWeeklyDigest's
// shape: gated by daily_digest_enabled, dedupes via last_daily_digest_at (20h
// window so the once-per-day scheduler tick stays idempotent even if the
// process restarts), renders directly from gatherWhatsNew(now - 24h) — no AI
// call. Pre-formats both HTML and plain-text bodies. Skips entirely if there's
// nothing new (empty digest is noise, not signal).
function renderDailyDigestEmail(data) {
  const fmtUsd = (n) => "$" + (n >= 0 ? "" : "-") + Math.abs(n).toFixed(2);
  const fmtDate = (d) => d ? new Date(d).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "";

  const txnsHtml = (data.transactions || []).slice(0, 15).map(t =>
    `<li style="margin:4px 0;color:#cccccc;">
       <span style="color:#888;font-size:11px;">${fmtDate(t.date)}</span>
       <strong style="color:#ffffff;">${escapeHtml(t.merchant || "(no merchant)")}</strong>
       <span style="color:#d4a574;">${fmtUsd(parseFloat(t.amount))}</span>
       ${t.category ? `<span style="color:#888;font-size:11px;"> · ${escapeHtml(t.category)}</span>` : ""}
     </li>`
  ).join("");
  const balanceHtml = (data.balance_changes || []).slice(0, 10).map(b => {
    const col = b.delta >= 0 ? "#9fd4c9" : "#eb6b6b";
    const sgn = b.delta >= 0 ? "+" : "";
    return `<li style="margin:4px 0;color:#cccccc;">
       <strong style="color:#ffffff;">${escapeHtml(b.account_name || "Account #" + b.source_id)}</strong>
       <span style="color:${col};">${sgn}${fmtUsd(b.delta).replace("$-", "-$").replace("$", "$")}</span>
       <span style="color:#888;font-size:11px;"> (${fmtUsd(b.baseline_balance)} → ${fmtUsd(b.current_balance)})</span>
     </li>`;
  }).join("");
  const subsHtml = (data.subscriptions || []).slice(0, 10).map(s =>
    `<li style="margin:4px 0;color:#cccccc;">
       <strong style="color:#ffffff;">${escapeHtml(s.display_name)}</strong>
       <span style="color:#d4a574;">${fmtUsd(parseFloat(s.amount))}</span>
       <span style="color:#888;font-size:11px;"> every ${s.cadence_days}d</span>
     </li>`
  ).join("");
  const notifsHtml = (data.notifications || []).slice(0, 10).map(n =>
    `<li style="margin:4px 0;color:#cccccc;">
       <strong style="color:#ffffff;">${escapeHtml(n.title || "")}</strong>
       <span style="color:#888;font-size:11px;"> ${escapeHtml(n.body || "")}</span>
     </li>`
  ).join("");

  const section = (title, color, html) => html ? `
    <h3 style="color:${color};font-size:14px;margin:18px 0 6px;font-weight:600;">${title}</h3>
    <ul style="list-style:none;padding:0;margin:0;">${html}</ul>` : "";

  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#080b12;font-family:Inter,system-ui,sans-serif;">
    <div style="max-width:640px;margin:0 auto;padding:32px 24px;">
      <div style="text-align:center;margin-bottom:24px;">
        <h1 style="color:#d4a574;font-size:22px;margin:12px 0 4px;font-weight:300;">Yesterday in Perfin</h1>
        <p style="color:#888888;font-size:12px;margin:0;">${new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}</p>
      </div>
      <div style="background:#0f1320;border:1px solid #1a1f35;border-radius:12px;padding:24px;">
        ${section("Balance changes", "#9fd4c9", balanceHtml)}
        ${section("New transactions", "#d4a574", txnsHtml)}
        ${section("New subscriptions detected", "#f0c36d", subsHtml)}
        ${section("Notifications", "#7fb5e6", notifsHtml)}
      </div>
      <div style="text-align:center;margin-top:24px;padding-top:16px;border-top:1px solid #1a1f35;">
        <p style="color:#666666;font-size:11px;margin:0;">Generated by Perfin · Daily Digest</p>
      </div>
    </div>
  </body></html>`;
}

function renderDailyDigestText(data) {
  const lines = ["YESTERDAY IN PERFIN", ""];
  if ((data.balance_changes || []).length) {
    lines.push("BALANCE CHANGES");
    for (const b of data.balance_changes.slice(0, 10)) {
      const sgn = b.delta >= 0 ? "+" : "";
      lines.push(`  ${b.account_name || "Account #" + b.source_id}: ${sgn}$${Math.abs(b.delta).toFixed(2)}`);
    }
    lines.push("");
  }
  if ((data.transactions || []).length) {
    lines.push("NEW TRANSACTIONS");
    for (const t of data.transactions.slice(0, 15)) {
      lines.push(`  ${t.merchant || "(no merchant)"} — $${parseFloat(t.amount).toFixed(2)}`);
    }
    lines.push("");
  }
  if ((data.subscriptions || []).length) {
    lines.push("NEW SUBSCRIPTIONS");
    for (const s of data.subscriptions.slice(0, 10)) {
      lines.push(`  ${s.display_name}: $${parseFloat(s.amount).toFixed(2)} every ${s.cadence_days}d`);
    }
    lines.push("");
  }
  if ((data.notifications || []).length) {
    lines.push("NOTIFICATIONS");
    for (const n of data.notifications.slice(0, 10)) {
      lines.push(`  ${n.title}: ${n.body}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function renderInsightEmail(text, modules, auditResult) {
  // HTML-escape FIRST so user/model text can't inject tags, THEN apply the
  // markdown patterns to the escaped output. Wrap consecutive <li> rows in
  // a <ul> so the resulting HTML is well-formed (some mail clients refuse
  // to render bare list items). The dashboard widget does the same wrap.
  let body = text
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/^### (.+)$/gm, '<h3 style="color:#d4a574;font-size:16px;margin:18px 0 8px;font-weight:600;">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="color:#d4a574;font-size:18px;margin:20px 0 10px;font-weight:600;">$1</h2>')
    .replace(/\*\*(.+?)\*\*/g, '<strong style="color:#ffffff;">$1</strong>')
    .replace(/^[\-\*] (.+)$/gm, '<li style="margin:4px 0;color:#cccccc;">$1</li>')
    // Wrap each run of consecutive <li> blocks in a single <ul>. The
    // alternative — leaving bare <li> — works in most browsers but several
    // email clients (Outlook desktop, older Gmail) skip rendering.
    .replace(/(<li[^>]*>[\s\S]*?<\/li>(?:\s*<li[^>]*>[\s\S]*?<\/li>)*)/g,
             '<ul style="margin:8px 0;padding-left:20px;">$1</ul>')
    .replace(/\n/g, "<br>");

  let auditSection = "";
  // Guard summary existence (AI-12) — auditInsight always returns it today, but
  // a future change shouldn't be able to throw inside email rendering.
  if (auditResult && auditResult.summary && (auditResult.summary.critical > 0 || auditResult.summary.warning > 0)) {
    auditSection = `
      <div style="margin-top:24px;padding:16px;background:#2a1a1a;border:1px solid #663333;border-radius:8px;">
        <h3 style="color:#eb6b6b;margin:0 0 8px;font-size:14px;">Audit Findings</h3>
        <p style="color:#cccccc;font-size:12px;margin:0;">${auditResult.summary.critical} critical, ${auditResult.summary.warning} warning issue(s) detected. Review in Settings &rarr; AI Insights.</p>
      </div>`;
  }

  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#080b12;font-family:Inter,system-ui,sans-serif;">
    <div style="max-width:640px;margin:0 auto;padding:32px 24px;">
      <div style="text-align:center;margin-bottom:24px;">
        <div style="display:inline-block;width:40px;height:40px;background:#d4a574;mask:url('data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 40 40%22><circle cx=%2220%22 cy=%2220%22 r=%2217%22 stroke=%22white%22 stroke-width=%222%22 fill=%22none%22/><circle cx=%2220%22 cy=%2220%22 r=%228%22 stroke=%22white%22 stroke-width=%221.5%22 fill=%22none%22/><circle cx=%2220%22 cy=%2220%22 r=%223%22 fill=%22white%22/></svg>') center/contain no-repeat;-webkit-mask:url('data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 40 40%22><circle cx=%2220%22 cy=%2220%22 r=%2217%22 stroke=%22white%22 stroke-width=%222%22 fill=%22none%22/><circle cx=%2220%22 cy=%2220%22 r=%228%22 stroke=%22white%22 stroke-width=%221.5%22 fill=%22none%22/><circle cx=%2220%22 cy=%2220%22 r=%223%22 fill=%22white%22/></svg>') center/contain no-repeat;"></div>
        <h1 style="color:#d4a574;font-size:22px;margin:12px 0 4px;font-weight:300;">Perfin Financial Analysis</h1>
        <p style="color:#888888;font-size:12px;margin:0;">${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
      </div>
      <div style="background:#0f1320;border:1px solid #1a1f35;border-radius:12px;padding:24px;color:#cccccc;font-size:13px;line-height:1.7;">
        ${body}
      </div>
      ${auditSection}
      <div style="text-align:center;margin-top:24px;padding-top:16px;border-top:1px solid #1a1f35;">
        <p style="color:#666666;font-size:11px;margin:0;">Modules: ${modules.join(", ")}</p>
        <p style="color:#555555;font-size:10px;margin:8px 0 0;">Generated by Perfin &middot; <a href="#" style="color:#5a8f8f;">Open Dashboard</a></p>
      </div>
    </div>
  </body></html>`;
}

module.exports = {
  renderInsightEmail,
  renderWeeklyDigestEmail,
  renderWeeklyDigestText,
  renderDailyDigestEmail,
  renderDailyDigestText,
  escapeHtml,
};
